//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public int LanguageId { get; set; }
        public string Name { get; set; }
        public Nullable<int> LevelId { get; set; }
        public int ResumeId { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual ResumeDetail ResumeDetail { get; set; }
    }
}
